language: java
script: ./gradlew build --build-cache -PVERSION=0.1.0 -PBINTRAY_USER=${BINTRAY_USER} -PBINTRAY_KEY=${BINTRAY_KEY}
deploy:
  provider: releases
  api_key: ${OAUTH_TOKEN}
  file_glob: true
  file: ./build/libs/*
  skip_cleanup: true
  on:
    tags: true