language: java
before_script:
- chmod +x gradlew
script:
- ./gradlew check
- ./gradlew codeCoverageReport
- ./gradlew build
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: ${OAUTH_TOKEN}
  file_glob: true
  file: ./build/libs/*
  skip_cleanup: true
  on:
    tags: true